@url = http://localhost:5000/employees-module

@emloyeeId = 8a8b82c0-109a-47d6-8805-45cea16cf9a1


###
GET {{url}}

###
GET {{url}}/Employees

###
GET {{url}}/Employees/{{emloyeeId}}

###
POST {{url}}/Employees
Content-Type: application/json
{
  "Firstname" : "John",
  "Lastname" : "Dow"
}

###
GET {{url}}/Employees/{{emloyeeId}}

###
PUT {{url}}/Employees
Content-Type: application/json
{
  "Id": "{{emloyeeId}}",
  "Firstname" : "John",
  "Lastname" : "Dow",
  "Description": "Opis pracownika"
}

###
DELETE {{url}}/Employees/{{emloyeeId}}
Content-Type: application/json
