@url = http://localhost:5000/users-module
@name = aaa
@email = user4@mycar.it
@password = aaa
@role = admin
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NjZjYzdjMS05Mjc3LTQ0N2YtOTM2Ny1kMDI5MTQzYjYyYjkiLCJ1bmlxdWVfbmFtZSI6Ijc2NmNjN2MxLTkyNzctNDQ3Zi05MzY3LWQwMjkxNDNiNjJiOSIsImp0aSI6IjkzMmVhMDFiLWViNDktNDAzNS1hNDVlLWU3ZDBmNGUzNmJkZSIsImlhdCI6IjE3MzMxNTU4MTM5ODgiLCJyb2xlIjoidXNlciIsImlzcyI6Ik15Q2FyIiwiZXhwIjoxNzMzMTU5NDEzLCJuYmYiOjE3MzMxNTU4MTN9.3IYQ_mXyh0WORHL8aly8KtR3UNwizoNezL9zrEJjZRQ

###
GET {{url}}

### 
GET {{url}}/account
Authorization: Bearer {{accessToken}}

### 
GET {{url}}/account/changepassword
Authorization: Bearer {{accessToken}}

### 
POST {{url}}/account/sign-up 
Content-Type: application/json
{
  "name": "{{name}}", 
  "email": "{{email}}", 
  "password": "{{password}}", 
  "role": "{{role}}", 
  "claims": {
    "permissions": 
    [
      "conferences", 
      "hosts", 
      "speakers", 
      "tickets", 
      "users"
    ]
  }
}

### 
POST {{url}}/account/sign-in 
Content-Type: application/json
{
  "identifier": "{{email}}",
  "password": "{{password}}"
}

###
POST {{url}}/account/forgot-password
Content-Type: application/json
{
  "email": "{{email}}",
}

