@url = http://localhost:5000/users-module
@name = ddd
@email = user6@mycar.it
@password = ddd
@role = admin
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMzMyNDQzNS1iODM2LTQxYzktYjM4MC03ZjYyMDlkYzU3MWYiLCJ1bmlxdWVfbmFtZSI6IjAzMzI0NDM1LWI4MzYtNDFjOS1iMzgwLTdmNjIwOWRjNTcxZiIsImp0aSI6ImEyNGYyYWQwLWM0ZmItNDliMC04OWY4LTI5N2JlNDlkMmZjMSIsImlhdCI6IjE3MzQ1NTQ5NTciLCJyb2xlIjoidXNlciIsImlzcyI6Ik15Q2FyIiwiZXhwIjoxNzM0NTU4NTU3LCJuYmYiOjE3MzQ1NTQ5NTd9.JBY5yUnp4Mj7xuABCfX7Bn9Ml9euyi-Q8gJONzt793k

###
GET {{url}}

### 
GET {{url}}/account

### 
PUT {{url}}/account/logout

### 
GET {{url}}/account/changepassword
Authorization: Bearer {{accessToken}}

### 
POST {{url}}/account/sign-up 
Content-Type: application/json
{
  "name": "{{name}}", 
  "email": "{{email}}", 
  "password": "{{password}}", 
  "role": "{{role}}", 
  "claims": {
    "permissions": 
    [
      "conferences", 
      "hosts", 
      "speakers", 
      "tickets", 
      "users"
    ]
  }
}

### 
POST {{url}}/account/sign-in 
Content-Type: application/json
{
  "identifier": "{{email}}",
  "password": "{{password}}"
}

### 
POST {{url}}/account/sign-in 
Content-Type: application/json
{
  "identifier": "ddd",
  "password": "ddd"
}

###
POST {{url}}/account/forgot-password
Content-Type: application/json
{
  "email": "{{email}}",
}

